### ISSUE TITLE
配置不全？

### ISSUE THREAD

**Issue by windyliu715** [nzai/stockrecorder#1]
2018/08/14 19:54:39 [America] 获取历史数据时发生错误: oss: service returned error: StatusCode=400, ErrorCode=InvalidBucketName, ErrorMessage=The specified bucket is not valid., RequestId=5B72C2FF2432E3C88CEC90CA
2018/08/14 19:54:39 [China] 获取历史数据时发生错误: oss: service returned error: StatusCode=400, ErrorCode=InvalidBucketName, ErrorMessage=The specified bucket is not valid., RequestId=5B72C2FF8A0E923225E54CF8
2018/08/14 19:54:44 [HongKong] 共有13559家上市公司
2018/08/14 19:54:44 [HongKong] 获取历史数据时发生错误: oss: service returned error: StatusCode=400, ErrorCode=InvalidBucketName, ErrorMessage=The specified bucket is not valid., RequestId=5B72C3048A0E923225E56C2A

**Comment by nzai** [comment]
@windyliu715  是的，需要修改config.yaml，写上你自己的配置
```
aliyun:
    oss:
        endpoint: "endpoint"
        id: "id"
        secret: "secret"
        bucket: "bucket"
        keyroot: "keyroot"
```
